version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nebchr_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./logs:/var/log/nginx
      - ./app:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - nebchr_network
    links:
      - redis
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nebchr_php
    restart: always
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ./app:/var/www/app
    networks:
      - nebchr_network
    links:
      - redis

  mysql:
    image: mysql:8
    container_name: nebchr_mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ""
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nebchr_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nebchr_phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - nebchr_network

  redis:
    container_name: nebchr_redis
    image: "redis:alpine"
    command: redis-server
    restart: always
    expose:
      - 6379
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - nebchr_network

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: nebchr_redismanager
    depends_on:
      - redis
    links:
      - redis
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: admin
      REDIS_1_NAME: MyRedis
      REDIS_1_HOST: redis
    ports:
      - ${PHP_REDIS_ADMIN_PORT}:80
    networks:
      - nebchr_network

networks:
  nebchr_network:
    external: true

volumes:
  mysql:
  redis-data:
  redis-conf:
