
push:
	symfony console d:d:d --force
	symfony console d:d:c
	symfony console d:m:m
	symfony console d:f:l

dd:
	symfony console d:d:d --force

dc:
	symfony console d:d:c

fl:
	symfony console d:f:l

mm:
	symfony console make:migration

dm:
	symfony console d:m:m
